/**
 * Character -> USB HID keycode, for typing text over the `hid` RPC.
 *
 * GENERATED by scripts/gen-keymap.mjs from idb's hid.py — do not edit by hand.
 * The mapping lives in idb's Python client, not the companion: `hid` carries
 * only raw key events, so this table is ours to own now.
 *
 * Coverage is printable ASCII (0x20-0x7E) plus newline. Anything else has no
 * keycode and must be rejected before a single event is sent.
 */

/** Left-shift keycode, held around characters that need it. */
export const HID_KEY_SHIFT = 225;

export type KeyStroke = { keycode: number; shift: boolean };

export const KEY_MAP: Readonly<Record<string, KeyStroke>> = {
  "a": { keycode: 4, shift: false },
  "b": { keycode: 5, shift: false },
  "c": { keycode: 6, shift: false },
  "d": { keycode: 7, shift: false },
  "e": { keycode: 8, shift: false },
  "f": { keycode: 9, shift: false },
  "g": { keycode: 10, shift: false },
  "h": { keycode: 11, shift: false },
  "i": { keycode: 12, shift: false },
  "j": { keycode: 13, shift: false },
  "k": { keycode: 14, shift: false },
  "l": { keycode: 15, shift: false },
  "m": { keycode: 16, shift: false },
  "n": { keycode: 17, shift: false },
  "o": { keycode: 18, shift: false },
  "p": { keycode: 19, shift: false },
  "q": { keycode: 20, shift: false },
  "r": { keycode: 21, shift: false },
  "s": { keycode: 22, shift: false },
  "t": { keycode: 23, shift: false },
  "u": { keycode: 24, shift: false },
  "v": { keycode: 25, shift: false },
  "w": { keycode: 26, shift: false },
  "x": { keycode: 27, shift: false },
  "y": { keycode: 28, shift: false },
  "z": { keycode: 29, shift: false },
  "A": { keycode: 4, shift: true },
  "B": { keycode: 5, shift: true },
  "C": { keycode: 6, shift: true },
  "D": { keycode: 7, shift: true },
  "E": { keycode: 8, shift: true },
  "F": { keycode: 9, shift: true },
  "G": { keycode: 10, shift: true },
  "H": { keycode: 11, shift: true },
  "I": { keycode: 12, shift: true },
  "J": { keycode: 13, shift: true },
  "K": { keycode: 14, shift: true },
  "L": { keycode: 15, shift: true },
  "M": { keycode: 16, shift: true },
  "N": { keycode: 17, shift: true },
  "O": { keycode: 18, shift: true },
  "P": { keycode: 19, shift: true },
  "Q": { keycode: 20, shift: true },
  "R": { keycode: 21, shift: true },
  "S": { keycode: 22, shift: true },
  "T": { keycode: 23, shift: true },
  "U": { keycode: 24, shift: true },
  "V": { keycode: 25, shift: true },
  "W": { keycode: 26, shift: true },
  "X": { keycode: 27, shift: true },
  "Y": { keycode: 28, shift: true },
  "Z": { keycode: 29, shift: true },
  "1": { keycode: 30, shift: false },
  "2": { keycode: 31, shift: false },
  "3": { keycode: 32, shift: false },
  "4": { keycode: 33, shift: false },
  "5": { keycode: 34, shift: false },
  "6": { keycode: 35, shift: false },
  "7": { keycode: 36, shift: false },
  "8": { keycode: 37, shift: false },
  "9": { keycode: 38, shift: false },
  "0": { keycode: 39, shift: false },
  "\n": { keycode: 40, shift: false },
  ";": { keycode: 51, shift: false },
  "=": { keycode: 46, shift: false },
  ",": { keycode: 54, shift: false },
  "-": { keycode: 45, shift: false },
  ".": { keycode: 55, shift: false },
  "/": { keycode: 56, shift: false },
  "`": { keycode: 53, shift: false },
  "[": { keycode: 47, shift: false },
  "\\": { keycode: 49, shift: false },
  "]": { keycode: 48, shift: false },
  "'": { keycode: 52, shift: false },
  " ": { keycode: 44, shift: false },
  "!": { keycode: 30, shift: true },
  "@": { keycode: 31, shift: true },
  "#": { keycode: 32, shift: true },
  "$": { keycode: 33, shift: true },
  "%": { keycode: 34, shift: true },
  "^": { keycode: 35, shift: true },
  "&": { keycode: 36, shift: true },
  "*": { keycode: 37, shift: true },
  "(": { keycode: 38, shift: true },
  ")": { keycode: 39, shift: true },
  "_": { keycode: 45, shift: true },
  "+": { keycode: 46, shift: true },
  "{": { keycode: 47, shift: true },
  "}": { keycode: 48, shift: true },
  ":": { keycode: 51, shift: true },
  "\"": { keycode: 52, shift: true },
  "|": { keycode: 49, shift: true },
  "<": { keycode: 54, shift: true },
  ">": { keycode: 55, shift: true },
  "?": { keycode: 56, shift: true },
  "~": { keycode: 53, shift: true },
};

/** Characters with no keycode, in input order. Empty means the text is typeable. */
export function unmappedCharacters(text: string): string[] {
  return [...text].filter((c) => !(c in KEY_MAP));
}
