#!/usr/bin/env node
/**
 * Regenerates packages/simgadget/src/idb/keymap.ts from idb's Python client.
 *
 * The text->keycode table is client-side in idb: the `hid` RPC only carries raw
 * key events, so dropping the Python CLI means owning this mapping. Deriving it
 * mechanically keeps it honest across submodule bumps — re-run this whenever
 * vendor/idb moves.
 *
 * Usage: node scripts/gen-keymap.mjs [path/to/idb/common/hid.py]
 */
import fs from "fs";
import path from "path";

const DEFAULT_SOURCES = [
  "vendor/idb/idb/common/hid.py",
  "../idb/idb/common/hid.py",
];

const source =
  process.argv[2] ?? DEFAULT_SOURCES.find((p) => fs.existsSync(p));
if (!source || !fs.existsSync(source)) {
  console.error(
    `Cannot find hid.py. Tried: ${DEFAULT_SOURCES.join(", ")}\n` +
      `Pass the path explicitly: node scripts/gen-keymap.mjs <path>`
  );
  process.exit(1);
}

const text = fs.readFileSync(source, "utf-8");

/** Decodes a Python string literal (single or double quoted, simple escapes). */
function decodePyString(literal) {
  const quote = literal[0];
  const body = literal.slice(1, -1);
  let out = "";
  for (let i = 0; i < body.length; i++) {
    if (body[i] !== "\\") {
      out += body[i];
      continue;
    }
    const next = body[++i];
    if (next === "n") out += "\n";
    else if (next === "t") out += "\t";
    else if (next === "r") out += "\r";
    else if (next === "\\") out += "\\";
    else if (next === quote) out += quote;
    else throw new Error(`Unhandled escape \\${next} in ${literal}`);
  }
  return out;
}

// Only scan the KEY_MAP block, so unrelated calls elsewhere can't leak in.
const blockStart = text.indexOf("KEY_MAP: dict[str, list[HIDEvent]] = {");
if (blockStart === -1) throw new Error("KEY_MAP not found in " + source);
const blockEnd = text.indexOf("\n}", blockStart);
const block = text.slice(blockStart, blockEnd);

// The trailing comma is optional: Python allows the final dict entry without
// one, and requiring it here would silently drop that character. The coverage
// check below would not catch it either if the dropped entry were "\n", which
// sits outside the printable-ASCII range it asserts on.
const entryRe =
  /^\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'):\s*key_press(_shifted)?_to_events\((\d+)\),?\s*$/gm;

const entries = [];
for (const m of block.matchAll(entryRe)) {
  entries.push({
    char: decodePyString(m[1]),
    shift: Boolean(m[2]),
    keycode: Number(m[3]),
  });
}

if (entries.length === 0) throw new Error("Parsed no KEY_MAP entries");

const seen = new Set();
for (const e of entries) {
  if (seen.has(e.char)) throw new Error(`Duplicate key for ${JSON.stringify(e.char)}`);
  seen.add(e.char);
}

const lines = entries.map(
  (e) =>
    `  ${JSON.stringify(e.char)}: { keycode: ${e.keycode}, shift: ${e.shift} },`
);

const out = `/**
 * Character -> USB HID keycode, for typing text over the \`hid\` RPC.
 *
 * GENERATED by scripts/gen-keymap.mjs from idb's ${path.basename(source)} — do not edit by hand.
 * The mapping lives in idb's Python client, not the companion: \`hid\` carries
 * only raw key events, so this table is ours to own now.
 *
 * Coverage is printable ASCII (0x20-0x7E) plus newline. Anything else has no
 * keycode and must be rejected before a single event is sent.
 */

/** Left-shift keycode, held around characters that need it. */
export const HID_KEY_SHIFT = 225;

export type KeyStroke = { keycode: number; shift: boolean };

export const KEY_MAP: Readonly<Record<string, KeyStroke>> = {
${lines.join("\n")}
};

/** Characters with no keycode, in input order. Empty means the text is typeable. */
export function unmappedCharacters(text: string): string[] {
  return [...text].filter((c) => !(c in KEY_MAP));
}
`;

const dest = "packages/simgadget/src/idb/keymap.ts";
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`Wrote ${dest}: ${entries.length} characters from ${source}`);

// Printable ASCII is what the ui_type schema admits, so any hole there is a
// regression the moment it appears.
const missing = [];
for (let c = 0x20; c <= 0x7e; c++) {
  if (!seen.has(String.fromCharCode(c))) missing.push(String.fromCharCode(c));
}
if (missing.length) {
  console.error(`Printable ASCII not covered: ${JSON.stringify(missing.join(""))}`);
  process.exit(1);
}
console.log("Printable ASCII 0x20-0x7E fully covered.");
